api_app/SNSDashboard/SNSDashboard/Models/ErrorViewModel.cs
using System;

namespace SNSDashboard.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

api_app/SNSDashboard/SNSDashboard/Models/ScanImageModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SNSDashboard.Models
{
    public class ScanImageModel
    {
        [JsonIgnore]
        public Guid Id { get; set; }
        [Required]
        public string Sku { get; set; }
        [Required]
        public string SerialNumber { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Images { get; set; }
        public DateTime CreatedOn { get; set; }
    }
}

api_app/SNSDashboard/SNSDashboard/Controllers/DashboardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SNS.Services.DTOs;
using SNS.Services.Interfaces;
using SNSDashboard.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace SNSDashboard.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IScanImagesService _scanImagesService;
        private readonly IMapper _mapper;

        public DashboardController(IScanImagesService scanImagesService, IMapper mapper)
        {
            _mapper = mapper;
            _scanImagesService = scanImagesService;
        }

        // GET: api/Products
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// GET: api/Products
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> GetScanImagesList()
        {
            try
            {
                var data = await _scanImagesService.Get();
                return Json(new { data });
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

    }
}

api_app/SNSDashboard/SNSDashboard/Controllers/ImageDataController.cs
using AutoMapper; 
using Microsoft.AspNetCore.Mvc;
using SNS.Services.DTOs;
using SNS.Services.Interfaces;
using SNSDashboard.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks; 

namespace SNSDashboard.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ImageDataController : ControllerBase
    {
        private readonly IScanImagesService _scanImagesService;
        private readonly IMapper _mapper;

        public ImageDataController(IScanImagesService scanImagesService, IMapper mapper)
        {
            _mapper = mapper;
            _scanImagesService = scanImagesService;
        }


        /// <summary>
        /// Create
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost("Create")]
        public async Task<ActionResult> Create(ScanImageModel model)
        {
            try
            {
                if (!ModelState.IsValid) return Ok(new { error = "Data is not valid." });

                var data = _mapper.Map<ScanImageRequest>(model);
                var result = await _scanImagesService.Create(data);

                return Ok(result);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}

api_app/SNSDashboard/SNSDashboard/Views/Dashboard/Index.cshtml
@{
    Layout = "_Layout";
}

<link href="~/js/dataTables.bootstrap4.css" rel="stylesheet" />

<div class="container">
    <table id="scanImages" class="ui celled table" width="100%">
        <thead>
            <tr>
                <th>SKU</th>
                <th>Serial Number</th>
                <th>Description</th>
                <th>Image</th>
                <th>Created On</th>
            </tr>
        </thead>
    </table>
</div>

<script language="JavaScript" type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" src="~/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="~/js/dataTables.bootstrap4.js" .></script>
<script type="text/javascript" src="~/js/dataTables.buttons.js"></script>
<script type="text/javascript" src="~/js/dataTables.responsive.js"></script>
<script>
    $(document).ready(function () {
        $('#scanImages').DataTable({
            processing: true,
            ordering: true,
            paging: true,
            searching: true,
            "ajax": {
                "url": '/Dashboard/GetScanImagesList',
                "type": "GET",
                "datatype": "json"
            },
            columns: [
                { "data": "sku", "name": "Sku", "autoWidth": true },
                { "data": "serialNumber", "name": "SerialNumber", "autoWidth": true },
                { "data": "description", "name": "Description", "autoWidth": true },
                {
                    render: function (data, type, row) {
                        return "<img width='30px' height='30px' src='/images/" + row.images + "'/>";
                    }
                },
                {
                    "data": "createdOn", "name": "CreatedOn", "autoWidth": true,
                    "render": function (data) {
                        var date = new Date(data);
                        var month = date.getMonth() + 1;
                        return (month.toString().length > 1 ? month : "0" + month) + "/" + date.getDate() + "/" + date.getFullYear();
                    }
                },

            ],

        });
    });
</script>

api_app/SNSDashboard/SNSDashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SNSDashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Index">Images Dashboard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SNSDashboard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>